### PR TITLE
use Github Actions to build on Windows 32/64 bits and macOS

### PR DESCRIPTION
**Pull request by missdeer**

### CODE REVIEW

**Comment by bernds** [comment]
Hmm, I'm uncertain about this. On the one hand, this is awesome - thank you for your work. But I'm not entirely sure yet I feel confident about the security aspects of github actions. I'm reading up on these.

Can you elaborate why C++17 seems necessary for MacOS X? What were the errors you saw?

**Comment by missdeer** [comment]
I don't know what you are worrying about, you can use Github Actions as a normal CI service, for example, it can verifie whether the change committed breaks build on each tier 1 platform. 

`std::make_unique` requires C++14 or even C++20, ref https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique, you may find detail build logs at https://github.com/missdeer/q5Go/runs/610654704?check_suite_focus=true

**Comment by bernds** [comment]
I am a little uneasy about relying on third-party actions like install-qt-action (which could change behaviour). I guess that's unavoidable with the Qt dependency. Also, I don't really want to publish binaries I didn't build myself in a trusted environment, at least not as "official" ones.

It looks like these scripts build everything normally on each push, and then check a tag to determine if a release needs to be uploaded. Is this correct? I think I would like to avoid the second part and just keep these binaries as build artifacts. Could I just truncate the scripts after upload-artifact?

**Comment by missdeer** [comment]
I think I can catch your point. You can discard the binaries generated by GitHub Actions. As I have stated above, you may use GitHub Actions only for verifying build broken. I have updated the scripts.

**Comment by bernds** [comment]
Alright, I've added this. Thanks!

**Comment by bernds** [comment]
Can I ask for your help with this? I was trying to add a mingw64 build to the Windows workflow, and to make the artifact .zip file contain a top-level directory. You can look at the futile attempts in my recent commits. Do you know how to do this correctly?

**Comment by missdeer** [comment]
Well, I see you have made it work. 👍

**Comment by bernds** [comment]
Not really. The windeployqt step doesn't work right for mingw (libraries are missing), and the zip file is still without a top-level directory...

**Comment by missdeer** [comment]
Seems that windeployqt won't always work as expected, especially with MinGW. You can add additional steps to copy the missing libraries from `$GITHUB_WORKSPACE/Qt/(your_qt_version)/(your_arch)/bin`.

I found that upload_artifacts action will try to remove the top-level directory from the final zip package, and no matter the included file is zip package or not, it will pack the file/directory into a zip package. So there's no good solution for that.

**Pull request closed without merging**
